package com.f4.commentlike.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LikeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLikeAllPropertiesEquals(Like expected, Like actual) {
        assertLikeAutoGeneratedPropertiesEquals(expected, actual);
        assertLikeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLikeAllUpdatablePropertiesEquals(Like expected, Like actual) {
        assertLikeUpdatableFieldsEquals(expected, actual);
        assertLikeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLikeAutoGeneratedPropertiesEquals(Like expected, Like actual) {
        assertThat(actual)
            .as("Verify Like auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLikeUpdatableFieldsEquals(Like expected, Like actual) {
        assertThat(actual)
            .as("Verify Like relevant properties")
            .satisfies(a -> assertThat(a.getReelId()).as("check reelId").isEqualTo(expected.getReelId()))
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLikeUpdatableRelationshipsEquals(Like expected, Like actual) {
        // empty method
    }
}
